### ISSUE TITLE
Configuration options for any IOExcetion

### ISSUE THREAD

**Issue by SerhiiKryvokin** [making/retryable-client-http-request-interceptor#46]
I'm now working on lost vpn or internet connection scenarios  

Sometimes the exceptions I get don't fall into any of supported types  

For instance, jdk.internal.net.http.HttpClientImpl may throw regular IOException when connection is lost  

```
Caused by: java.io.IOException: Operation timed out
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:969) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133) ~[java.net.http:na]
	at org.springframework.http.client.JdkClientHttpRequest.executeInternal(JdkClientHttpRequest.java:103) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.http.client.AbstractStreamingClientHttpRequest.executeInternal(AbstractStreamingClientHttpRequest.java:70) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:112) ~[spring-web-6.1.14.jar:6.1.14]
	at am.ik.spring.http.client.RetryableClientHttpRequestInterceptor.intercept(RetryableClientHttpRequestInterceptor.java:194) ~[retryable-client-http-request-interceptor-0.5.1.jar:na]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:88) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.http.client.support.BasicAuthenticationInterceptor.intercept(BasicAuthenticationInterceptor.java:79) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:88) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:72) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchangeInternal(DefaultRestClient.java:492) ~[spring-web-6.1.14.jar:6.1.14]
	... 31 common frames omitted
Caused by: java.io.IOException: Operation timed out
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:340) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:294) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:269) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.implRead(SocketChannelImpl.java:426) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:493) ~[na:na]
	at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1178) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:841) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:782) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:965) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:1476) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:1421) ~[java.net.http:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597) ~[na:na]
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1421) ~[java.net.http:na]
```

Exceptions may vary depending on the place where code is executed at the time internet connection is lost  

What about adding an option to retry on any IOException or even any Exception?

**Comment by making** [comment]
Hi, thanks for the report.
Is it possible to reproduce the scenario in a test code?

`JdkClientHttpRequestFactory` is actually tested but the reported case is not captured.
https://github.com/making/retryable-client-http-request-interceptor/blob/develop/src/test/java/am/ik/spring/http/client/RetryableClientHttpRequestInterceptorTest.java#L85

**Comment by making** [comment]
> or even any Exception

`ClientHttpRequestInterceptor#intercept` throws `IOException`.
Do you want to handle `RuntimeException`? What kind of `RuntimeException` did you see?

**Comment by SerhiiKryvokin** [comment]
Nevermind, I'm not sure if there is any scenario to get some non-IO exception reasonable to retry  
Regarding IO-exceptions, I just tried to add apache httpclient5 to classpath so spring can use it  

Now the exception looks like this

```
Caused by: java.net.SocketException: Operation timed out
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:256) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:281) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[na:na]
```

Didn't manage to reproduce it from a test with MockServerRunner. I guess it is possible to reproduce it by mocking httpClient with a stub that throws IOException on any request

**Comment by making** [comment]
https://github.com/making/retryable-client-http-request-interceptor/commit/55533713eba5040d45116ed26c15343d1e2ea17c changes the way to configure which IOException to retry from boolean to `Predicate<IOException>` that allows you to configure any `Predicate<IOException>`.

Any change to try `0.6.0-SNAPSHOT`?

**Comment by making** [comment]
renamed a bit in 534cd09802fa94b6436e4cd89f197d82b05c2e63

**Comment by making** [comment]
Thanks for the confirmation!
I'll cut 0.6.0 release.

**Comment by making** [comment]
0.6.0 is now available on the central
https://repo1.maven.org/maven2/am/ik/spring/retryable-client-http-request-interceptor/0.6.0/
